CREATE DATABASE STUDENT_ENROLLMENT_;

USE STUDENT_ENROLLMENT_;

CREATE TABLE STUDENT(
STUDENT_ID INT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL
);

INSERT INTO STUDENT (STUDENT_ID,NAME) VALUES
(1001,'SATHIYA'),
(1002,'SATZ'),
(1003,'SARA');

CREATE TABLE COURSE(
COURSE_ID INT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL
);

INSERT INTO COURSE (COURSE_ID,NAME) VALUES
(1,'CORE JAVA'),
(2,'J2EE'),
(3,'SQL'),
(4,'WEB TECH');

ALTER TABLE STUDENT
ADD COLUMN CURRENTCOURSEID INT ,
ADD FOREIGN KEY (CURRENTCOURSEID) REFERENCES COURSE(COURSE_ID);

UPDATE STUDENT
SET CURRENTCOURSEID=1
WHERE STUDENT_ID IN (1001,1002);

UPDATE STUDENT
SET CURRENTCOURSEID=3
WHERE STUDENT_ID=1003;

SELECT * FROM STUDENT;

SELECT STUDENT.NAME AS STUDENTNAME,COURSE.NAME AS COURSENAME
FROM COURSE
INNER JOIN STUDENT 
ON STUDENT.CURRENTCOURSEID=COURSE.COURSE_ID;









